name: Release first_volume_exercise

on:
  push:
    branches: 
      - master
    paths:
      - 'exec_bash_exercise_and_first_volume_exercise/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        SECRET_MESSAGE: ${{ secrets.FIRST_VOLUME_EXERCISE_SECRET_MESSAGE }}
      with:
        name: devopsdockeruh/first_volume_exercise
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
        buildargs: SECRET_MESSAGE
        workdir: exec_bash_exercise_and_first_volume_exercise

  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v2

      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Buildx
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm,linux/arm64,linux/ppc64le,linux/s390x \
            --build-arg SECRET_MESSAGE=${{ secrets.FIRST_VOLUME_EXERCISE_SECRET_MESSAGE }} \
            --tag devopsdockeruh/first_volume_exercise:multiarch \
            --push ./exec_bash_exercise_and_first_volume_exercise
