name: Release ports_exercise

on:
  push:
    branches: 
      - master
    paths:
      - 'ports_exercise/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: devopsdockeruh/ports_exercise
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
        workdir: ports_exercise

  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v2

      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Buildx
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm,linux/arm64,linux/ppc64le,linux/s390x \
            --tag devopsdockeruh/ports_exercise:multiarch \
            --push ./ports_exercise
